apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: istio-system
  annotations:
  labels:
    app: jaeger
    jaeger-infra: jaeger-service
    release: istio
spec:
  type: NodePort
  ports:
    - name: query-http
      port: 16686
      nodePort: 30686
      protocol: TCP
      targetPort: 16686
  selector:
    app: jaeger